#!/bin/csh


set PLAT = "`uname -s`"
set DERT_PATH = $0:h
set MAX_MEM = 2048   # megabytes

if ($DERT_PATH == dert) then
	set DERT_PATH = "."
endif

if ($PLAT == Darwin) then

# The following paths may be used instead.
#	set path = ('/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin' $path) 

	java -Xms256m -Xmx${MAX_MEM}m -Xdock:icon=$DERT_PATH/derticon.icns -Xdock:name="DERT" -jar $DERT_PATH/dert.app/Contents/Java/dert.jar $argv

else

# The following path may be used instead.
#	set path = ('/etc/alternatives/java_sdk_1.7.0/bin' $path)

	java -Xms256m -Xmx${MAX_MEM}m -jar $DERT_PATH/dert.jar $argv

endif
	