#!/bin/csh

# This script gets the SPICE kernels and puts them in a directory called kernels.
# Run it from the DERT installation directory.

# Edit dert.properties to add or remove kernel files.

set PLAT = "`uname -s`"
set DERT_PATH = $0:h

if ($DERT_PATH == dert) then
	set DERT_PATH = "."
endif

if ($PLAT == Darwin) then

	set DEST = $DERT_PATH/dert.app/Contents/Java/kernels
else

	set DEST = $DERT_PATH/kernels
endif

# Gravitational constant x mass (GM) values
curl http://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/gm_de431.tpc > $DEST/gm_de431.tpc

# Generic orientation data
curl http://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00010.tpc > $DEST/pck00010.tpc

# Leapseconds kernel
curl http://naif.jpl.nasa.gov/pub/naif/generic_kernels/lsk/naif0011.tls > $DEST/naif0011.tls

# Generic Planet Ephemeris
curl http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430.bsp > $DEST/de430.bsp

# Update to de430 for New Horizons
curl http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de432s.bsp > $DEST/de432s.bsp

# Mars Planet Ephemeris
curl http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellite/mar097.bsp > $DEST/mar097.bsp

# Pluto Planet Ephemeris
curl http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellite/plu055.bsp > $DEST/plu055.bsp
