#!/bin/csh

set PLAT = "`uname -s`"
set DERT_PATH = $0:h
set MAX_MEM = 8192   # megabytes

if ($DERT_PATH == layerfactory) then
	set DERT_PATH = "."
endif

if ($PLAT == Darwin) then

# One of the following paths may be used instead.
#	set path = ('/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin' $path) 
#	set path = ('/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin' $path) 

	java -Xms256m -Xmx${MAX_MEM}m -classpath $DERT_PATH/dert.app/Contents/Java/dert.jar:$DERT_PATH/dert.app/Contents/Java/natives_macosx.jar gov.nasa.arc.dert.landscape.factory.LayerFactory $argv

else

# The following path may be used instead.
#	set path = ('/etc/alternatives/java_sdk_1.7.0/bin' $path)

	java -Xms256m -Xmx${MAX_MEM}m -classpath $DERT_PATH/dert.jar:$DERT_PATH/lib/natives_linux.jar gov.nasa.arc.dert.landscape.factory.LayerFactory $argv

endif
