/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_nasa_arc_dert_raster_geotiff_GTIF */

#ifndef _Included_gov_nasa_arc_dert_raster_geotiff_GTIF
#define _Included_gov_nasa_arc_dert_raster_geotiff_GTIF
#ifdef __cplusplus
extern "C" {
#endif
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_IMAGEWIDTH
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_IMAGEWIDTH 256L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_IMAGELENGTH
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_IMAGELENGTH 257L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_BITSPERSAMPLE
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_BITSPERSAMPLE 258L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_TILEWIDTH
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_TILEWIDTH 322L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_TILELENGTH
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_TILELENGTH 323L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_MINSAMPLEVALUE
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_MINSAMPLEVALUE 280L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_MAXSAMPLEVALUE
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_MAXSAMPLEVALUE 281L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_SAMPLESPERPIXEL
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_SAMPLESPERPIXEL 277L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_ROWSPERSTRIP
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_ROWSPERSTRIP 278L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_STRIPBYTECOUNTS
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_STRIPBYTECOUNTS 279L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_PLANARCONFIG
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_PLANARCONFIG 284L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_SAMPLEFORMAT
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_SAMPLEFORMAT 339L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_SMINSAMPLEVALUE
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_SMINSAMPLEVALUE 340L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_SMAXSAMPLEVALUE
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_SMAXSAMPLEVALUE 341L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_FILLORDER
#define gov_nasa_arc_dert_raster_geotiff_GTIF_TIFFTAG_FILLORDER 266L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_GDAL_NODATA_TAG
#define gov_nasa_arc_dert_raster_geotiff_GTIF_GDAL_NODATA_TAG 42113L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_GEO_KEY_DIRECTORY_TAG
#define gov_nasa_arc_dert_raster_geotiff_GTIF_GEO_KEY_DIRECTORY_TAG 34735L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_GEO_DOUBLE_PARAMS_TAG
#define gov_nasa_arc_dert_raster_geotiff_GTIF_GEO_DOUBLE_PARAMS_TAG 34736L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_GEO_ASCII_PARAMS_TAG
#define gov_nasa_arc_dert_raster_geotiff_GTIF_GEO_ASCII_PARAMS_TAG 34737L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_MODEL_TIEPOINT_TAG
#define gov_nasa_arc_dert_raster_geotiff_GTIF_MODEL_TIEPOINT_TAG 33922L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_MODEL_PIXEL_SCALE_TAG
#define gov_nasa_arc_dert_raster_geotiff_GTIF_MODEL_PIXEL_SCALE_TAG 33550L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_MODEL_TRANSFORMATION_TAG
#define gov_nasa_arc_dert_raster_geotiff_GTIF_MODEL_TRANSFORMATION_TAG 34264L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_PLANARCONFIG_CONTIG
#define gov_nasa_arc_dert_raster_geotiff_GTIF_PLANARCONFIG_CONTIG 1L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_PLANARCONFIG_SEPARATE
#define gov_nasa_arc_dert_raster_geotiff_GTIF_PLANARCONFIG_SEPARATE 2L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_UINT
#define gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_UINT 1L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_INT
#define gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_INT 2L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_IEEEFP
#define gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_IEEEFP 3L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_VOID
#define gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_VOID 4L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_COMPLEXINT
#define gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_COMPLEXINT 5L
#undef gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_COMPLEXIEEEFP
#define gov_nasa_arc_dert_raster_geotiff_GTIF_SAMPLEFORMAT_COMPLEXIEEEFP 6L

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    openTIFF
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_openTIFF
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    closeTIFF
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_closeTIFF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    getTIFFFieldString
 * Signature: (JI[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_getTIFFFieldString
  (JNIEnv *, jobject, jlong, jint, jobjectArray);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    getTIFFFieldInt
 * Signature: (JI[I)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_getTIFFFieldInt
  (JNIEnv *, jobject, jlong, jint, jintArray);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    getTIFFFieldShort
 * Signature: (JI[S)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_getTIFFFieldShort
  (JNIEnv *, jobject, jlong, jint, jshortArray);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    getTIFFFieldDouble
 * Signature: (JI[D)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_getTIFFFieldDouble
  (JNIEnv *, jobject, jlong, jint, jdoubleArray);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    getTIFFFieldFloat
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_getTIFFFieldFloat
  (JNIEnv *, jobject, jlong, jint, jfloatArray);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    setTIFFFieldString
 * Signature: (JILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_setTIFFFieldString
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    setTIFFFieldInt
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_setTIFFFieldInt
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    setTIFFFieldShort
 * Signature: (JIS)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_setTIFFFieldShort
  (JNIEnv *, jobject, jlong, jint, jshort);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    setTIFFFieldDouble
 * Signature: (JID)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_setTIFFFieldDouble
  (JNIEnv *, jobject, jlong, jint, jdouble);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    setTIFFFieldFloat
 * Signature: (JIF)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_setTIFFFieldFloat
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    setTIFFFieldIntArray
 * Signature: (JI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_setTIFFFieldIntArray
  (JNIEnv *, jobject, jlong, jint, jintArray);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    setTIFFFieldShortArray
 * Signature: (JI[S)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_setTIFFFieldShortArray
  (JNIEnv *, jobject, jlong, jint, jshortArray);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    setTIFFFieldDoubleArray
 * Signature: (JI[D)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_setTIFFFieldDoubleArray
  (JNIEnv *, jobject, jlong, jint, jdoubleArray);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    setTIFFFieldFloatArray
 * Signature: (JI[F)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_setTIFFFieldFloatArray
  (JNIEnv *, jobject, jlong, jint, jfloatArray);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    isTiled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_isTiled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    getNumberOfStrips
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_getNumberOfStrips
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    getStripSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_getStripSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    readStrip
 * Signature: (JILjava/nio/Buffer;J)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_readStrip
  (JNIEnv *, jobject, jlong, jint, jobject, jlong);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    readRGBAStrip
 * Signature: (JILjava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_readRGBAStrip
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    writeStrip
 * Signature: (JILjava/nio/Buffer;J)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_writeStrip
  (JNIEnv *, jobject, jlong, jint, jobject, jlong);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    getNumberOfTiles
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_getNumberOfTiles
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    getTileSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_getTileSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    readTile
 * Signature: (JILjava/nio/Buffer;J)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_readTile
  (JNIEnv *, jobject, jlong, jint, jobject, jlong);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    readRGBATile
 * Signature: (JIILjava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_readRGBATile
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    writeTile
 * Signature: (JILjava/nio/Buffer;J)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_writeTile
  (JNIEnv *, jobject, jlong, jint, jobject, jlong);

/*
 * Class:     gov_nasa_arc_dert_raster_geotiff_GTIF
 * Method:    getTIFFError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nasa_arc_dert_raster_geotiff_GTIF_getTIFFError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
